### ISSUE TITLE
Uncaught Error: Cannot find module 'async'

### ISSUE THREAD

**Issue by mimmi1234** [Zren/atom-a-package-loader#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.2
**Thrown From**: [a-package-loader](https://github.com/zren/atom-a-package-loader) package, v1.0.0
### Stack Trace

Uncaught Error: Cannot find module 'async'

```
At module.js:346

Error: Cannot find module 'async'
  at Module._resolveFilename (module.js:344:15)
  at Function.Module._resolveFilename (/Users/mimmi1234/Downloads/Atom.app/Contents/Resources/app/src/module-cache.js:380:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.module.exports.onWindowLoaded (/Users/mimmi1234/.atom/packages/a-package-loader/lib/main.coffee:152:14)
  at /Users/mimmi1234/.atom/packages/a-package-loader/lib/main.coffee:115:8

```
### Commands

```
```
### Config

```
{
  "core": {
    "disabledPackages": [
      "tabs",
      "tree-view"
    ]
  },
  "a-package-loader": {}
}
```
### Installed Packages

``` coffee
# User
Atom-Hack, v2.2.0
Xolotl, v1.0.0
a-package-loader, v1.0.0
atom-memolist-grep, v0.2.1
atom-python-debugger, v0.1.1
atom-text-transformer, v0.3.0
auto-host-markdown-image, v0.2.1
browser-refresh, v0.8.3
bug-report, v0.5.3
circle-ci, v0.3.0
coffeescript-be-gone, v0.1.0
color-picker, v1.2.6
craft-snippets, v0.4.2
emacs-flow, v0.1.0
emacs-mode, v0.0.29
feedback, v0.33.0
file-type-icons, v0.5.3
giphy, v0.1.0
gulp-snippets, v0.6.0
hide-files, v0.1.2
hipster-ipsum, v0.1.0
i18n-brackets, v0.1.0
inline-autocomplete, v0.3.3
laravel, v0.4.2
laravel-facades, v1.0.0
linter, v0.9.0
linter-flow, v0.1.3
linter-metascript, v0.0.3
linter-python-pep8, v0.2.0
linter-python-pyflakes, v0.1.0
minimap, v3.4.9
minimap-find-and-replace, v3.0.4
nbsp-detect, v0.0.1
outdoor-theme, v0.4.0
package-cop, v0.2.1
package-sync, v0.1.1
python, v0.5.1
python-for-glyphs, v0.1.0
python-isort, v0.0.5
racer, v0.8.0
regex-railroad-diagram, v0.6.3
remote-sync, v2.3.1
rss-ticker, v0.6.0
script-runner, v1.6.0
semaphore, v0.2.0
starcraft-tips, v0.1.0
sublime-tabs, v0.4.8
syntax-settings, v0.7.1
ti-build-atom, v0.7.0
travis-ci-status, v0.11.1
tree-ignore, v0.1.1
vim-mode, v0.22.0
wakatime, v2.0.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by Zren** [comment]
This package was more of an experiment. Guess I forgot to add `async` as a dependancy. Though I though atom used it as well. Guess not.
